### ISSUE TITLE
[skipjack]  WiFi needs a patch to run

### ISSUE THREAD

**Issue by beroset** [AsteroidOS/meta-smartwatch#208]
With this issue, I'd like to revive this 2021 pull request: https://github.com/AsteroidOS/meta-skipjack-hybris/pull/12

Although the suggestion in reply to that PR was to instead move the things done in that service file to `/etc/init.rc` the current kernel version in use does not have or use that file.

**Comment by MagneFire** [comment]
The original PR mentions `/init.rc` this should exist on most watches since it forms a core part of the Android system.

Regardless, I think it's better to use the original implementation as this works reliably.

On some watches we could also trigger this using the `boot_completed` action:
https://github.com/AsteroidOS/meta-smartwatch/blob/7c599168acea03da84137c50ec0f9a95c25f5d5e/meta-hoki/recipes-android/android-init/android-init/init.rc#L63

But this does not work on all watches as the `getprop`/`setprop` commands do not always change the android-init properties.
