### ISSUE TITLE
LG G Watch R stuck in boot loop

### ISSUE THREAD

**Issue by jackkaback** [AsteroidOS/meta-smartwatch#97]
My LG G Watch R is stuck in a boot loop while connected to the dock. It boots, I get the LG logo, and then I get the AsteroidOS logo before repeating.

**Comment by eLtMosen** [comment]
Is this a fresh flash? Then i would just try to flash again. Connection problems sometimes cause faulty flash processes.
Or did you run this lenok (LG Watch R) since longer time already with AOS and the boot loop appeared just now?
Did you possibly update via OPKG?
Thanks for reporting and helping to narrow the issue in.

**Comment by jackkaback** [comment]
Yes this is a fresh install, though when I am on the dock it's stuck in the boot loop. out of the dock it appears to only go to the LG screen, so I'm guessing it's too low on battery now. Even after connecting it to the main it only boot loops while getting hot.

**Comment by jackkaback** [comment]
Well, I let it stay attached to main for a while and it was stuck, so I did try doing a re-flashing, now however if I disconnect it from the dock it immediately powers down, even though it has 49% battery. Before putting on Asteroid it was able to stay on without being docked.

**Comment by jackkaback** [comment]
Scratch that, now it wants to work. Thanks for the assistance.
